name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: saucedemo-full-suite-cypress
          browser: chrome

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: saucedemo-full-suite/cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: saucedemo-full-suite/cypress/videos
          if-no-files-found: ignore

  cypress-realworld:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install app dependencies
        run: yarn install
        working-directory: cypress-realworld-app

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypresRealWorldAppTests
          browser: chrome
          start: yarn --cwd ../cypresRealWorldAppTests start
          wait-on: 'http://localhost:3000, http://localhost:3001'
          wait-on-timeout: 60

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-realworld-screenshots
          path: my-cypress-project/cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-realworld-videos
          path: my-cypress-project/cypress/videos
          if-no-files-found: ignore